//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class destination
    {
        public int destinationid { get; set; }
        public string destinationname { get; set; }
        public Nullable<int> cityid { get; set; }
        public string description { get; set; }
    
        public virtual city city { get; set; }
    }
}
