//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HOTELEntities : DbContext
    {
        public HOTELEntities()
            : base("name=HOTELEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrator> administrators { get; set; }
        public virtual DbSet<authorization> authorizations { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<hotel> hotels { get; set; }
        public virtual DbSet<street> streets { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<destination> destinations { get; set; }
    }
}
